webservice_key:
truncate_all: false
last_sync:
#tenant_column:
#tenant_mapping:
#  - identifier:
#    webservice_key:

db:
  connection_string: postgres://[usuário]:[senha]@[host]:[porta]/[database]?sslmode=disable

mappings:
  banners:
    abrir_em: href_target
    descricao: description
    id_banner: id
    id_imagem: image_id
    imagem: image_url
    is_video: is_video
    link: url
    ordem: order
    titulo: title
    video: video_url
  banners_table: banners
  brokers:
    avatar: avatar
    biografia: biography
    cargo: job_position
    cidade: city_name
    corretor: is_broker
    creci: creci
    data_nascimento: birthday
    depoimentos: testimonials
    email: email
    estado: state_abbrev
    facebook: facebook_url
    id: id
    instagram: instagram_url
    linkedin: linkedin_url
    mostrar_site: show_personal_website
    nome: name
    skype: skype_url
    telefone: primary_phone_number
    telefone_whatsapp: primary_phone_has_whatsapp
    telefone2: alt_phone_number
    telefone2_whatsapp: alt_phone_has_whatsapp
    twitter: twitter_url
    website: personal_website_url
  brokers_table: brokers
  condominiums:
    acabamentos: construction_percentage
    administradora: administering_company_name
    alvenaria: brick_percentage
    construtora: building_company_name
    data_cadastro: created_at
    data_update: updated_at
    destaque: featured
    endereco_bairro: address_neighborhood
    endereco_cep: address_zipcode
    endereco_cidade: city_name
    endereco_estado: state_name
    endereco_logradouro: address_street
    endereco_numero: address_number
    entrega_ano: delivery_year
    entrega_mes: delivery_month
    estruturas: structure_percentage
    etiquetas: labels
    fechado: gated
    fundacoes: foundation_percentage
    id_bairro: neighborhood_id
    id_cidade: city_id
    id_condominio: id
    id_estado: state_id
    id_imagem: cover_image_id
    imagens: images
    incorporadora: real_state_developer_name
    infraestruturas: infrastructures
    intalacoes: installations_percentage
    lancamento: launch
    latitude: latitude
    logotipo: cover_image
    longitude: longitude
    nome: name
    observacoes: notes
    paisagismo: landscaping_percentage
    plantas: blueprints
    projeto_arquitetonico: architect_name
    projeto_decoracao: decorator_name
    projeto_paisagismo: landscaper_name
    projetos: project_percentage
    registro_incorporacao: incorporation_record
    situacao: status
    terraplanagem: ground_leveling_percentage
    tipo: type
    total_imoveis_disponiveis: available_properties
    tour360: ar_tour
    videos: videos
  condominiums_table: condominiums
  properties:
    andar: address_floor
    andar_visivel: show_address_floor
    area_privativa: private_area
    area_total: total_area
    area_util: useful_area
    atividade_rural: rural_activities
    banheiros: bathrooms
    dormitorios: bedrooms
    calendario_temporada: season_calendar
    codigo: identifier_code
    condominio_comodidades: condominium_infrastructures
    condominio_fechado: gated_condominium
    condominio_nome: condominium_name
    condominio_tipo: condominium_type
    contrato: contracts
    data_atualizacao: validated_at
    data_cadastro: created_at
    descricao_anuncio: ad_description
    destaque: featured
    destaque_fim: feature_until
    distancia_mar: sea_distance
    endereco_bairro: address_neighborhood
    endereco_bairro_visivel: show_address_neighborhood
    endereco_cep: address_zipcode
    endereco_cidade: address_city
    endereco_cidade_visivel: show_address_city
    endereco_completamente_visivel: show_full_address
    endereco_estado: address_state
    endereco_estado_visivel: show_address_state
    endereco_logradouro: address_street
    endereco_logradouro_visivel: show_address_street
    endereco_numero: address_number
    endereco_numero_visivel: show_address_number
    endereco_referencia: address_reference
    endereco_referencia_visivel: show_address_reference
    entrega_ano: delivery_year
    entrega_mes: delivery_month
    exclusividade: has_exclusivity
    financiavel: financeable
    garagens: garages
    geoposicionamento_visivel: geoposition_visibility
    id_bairro: neighborhood_id
    id_cidade: city_id
    id_condominio: condominium_id
    id_corretor: broker_id
    id_estado: state_id
    id_imovel: id
    imagens: images
    imovel_comodidades: property_infrastructures
    latitude: latitude
    longitude: longitude
    medida: measurement_type
    meta_description: meta_description
    meta_title: meta_title
    mobiliado: furnished
    numero_pessoas: allowed_guests
    observacoes: notes
    periodicidade_iptu: iptu_frequency
    permuta: accept_exchange
    plantas: blueprints
    posicao: position
    posicao_solar: solar_positions
    rural_area_aravel: arable_area
    rural_sedes: rural_headquarters
    seguro_fianca: surety_insurance
    situacao: occupancy_status
    status: building_status
    subtipo: subtype
    suites: suites
    tags: labels
    terreno_direita: terrain_length_right
    terreno_esquerdo: terrain_length_left
    terreno_frente: terrain_width_front
    terreno_fundos: terrain_width_back
    terreno_total: terrain_area
    tipo: type
    tipo_construcao: building_type
    tipo_piso: floor_types
    titulo_anuncio: ad_title
    tour360: ar_tour
    updated_at: updated_at
    valor_condominio: condominium_value
    valor_condominio_visivel: show_condominium_value
    valor_iptu: iptu_value
    valor_iptu_isento: iptu_value_exempt
    valor_iptu_visivel: show_iptu_value
    valor_locacao: rental_value
    valor_locacao_visivel: show_rental_value
    valor_seguro_incendio: fire_insurance_value
    valor_taxa_limpeza: cleaning_fee_value
    valor_temporada: seasonal_value
    valor_temporada_visivel: show_seasonal_value
    valor_venda: sale_value
    valor_venda_visivel: show_sale_value
    videos: videos
  properties_table: properties
